version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
    - ./app:/app
    - ./samples:/samples
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    command: python3 -m app.main
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/db
    volumes:
      - ./db:/db
    ports:
      - 27017:27017
